### ISSUE TITLE
Mod for 1.1

### ISSUE THREAD

**Issue by coyoteclan** [BraXi/CoD1_Zombies_1.2_Mod#1]
Does this mod work with 1.1?
https://www.gamefront.com/games/call-of-duty/file/zombies-mod
If yes, can I have the server side scripts because I want to host a server.

**Comment by BraXi** [comment]
Over the years (14 it seems, huh) I have lost the files for earlier versions of this mod, but you can grab 1.2 right from this respository, 0.5 beta and 1.2 do not work with CoD 1.1 and were only tested with CoD 1.5, you'll likely need to edit the scripts yourself to make it compatible (remove cases where getguid() is used etc)..

**Comment by kazam0180** [comment]
Ok thanks
